MGMT-8077: Add "disk encryption" to cluster details
openshift-assisted/assisted-ui-lib pull request #1010
Opened 2021-12-09 06:02 UTC by DanielleChason

https://issues.redhat.com/browse/MGMT-8077

I added info about the disk encryption in the cluster details. 

***Please note** I had to make a small change in comparison to the mock (image of the mock can be found in the jira link above). 
 In the mock in case the diskEncyription is enabled for workers and masters the information is divided into two lines. 
In the project file trying to use <br> converts '<' to &lt and '>' to &gt, separating DetailsItem creates too big of a gap and using '\n' is not possible.

I'll be happy to here if that's OK or other suggestions. 

![image](https://user-images.githubusercontent.com/69599321/145278277-95f71c91-d521-42ca-bb10-8809195f8338.png)

2021-12-09 14:38 UTC, jkilzi requested changes

2021-12-09 14:38 UTC, jkilzi commented on src/ocm/components/clusterDetail/ClusterProperties.tsx
> +const getDiskEncryptionType = (diskEncryption: string | undefined): string => {
```suggestion
const getDiskEncryptionType = (diskEncryption: string | undefined): string => {
.............................................................................^
```
Is this any `string`? Can we constrain the types of strings this parameter can be assigned to?

2021-12-12 10:39 UTC, nirfarkas commented
Can you please keep the two lines? One for control plane nodes and the other for workers? This will scale up better if we want to add info about each.

2021-12-22 13:58 UTC, jkilzi requested changes

2021-12-22 13:58 UTC, jkilzi commented on src/ocm/components/clusterDetail/ClusterProperties.tsx
> +const getDiskEncryptionType = (diskEncryption: DiskEncryption['enableOn']) => {
```suggestion
const getDiskEncryptionEnabledOnStatus = (diskEncryption: DiskEncryption['enableOn']) => {
```

2021-12-22 13:58 UTC, jkilzi commented on src/ocm/components/clusterDetail/ClusterProperties.tsx
> +          value={getDiskEncryptionType(cluster.diskEncryption?.enableOn)}
```suggestion
          value={getDiskEncryptionEnabledOnStatus(cluster.diskEncryption?.enableOn)}
```

2021-12-22 13:59 UTC, jkilzi approved these changes

2021-12-22 14:01 UTC, jkilzi approved these changes

2021-12-22 14:02 UTC, merged