MGMT-8444: Update edit hostname dialog
openshift-assisted/assisted-ui-lib pull request #1029
Opened 2021-12-16 15:16 UTC by rawagner

![change_hostname](https://user-images.githubusercontent.com/2078045/148062742-8cbf3455-82f9-4bd1-be05-ed1571501bf1.gif)
![Screenshot from 2022-01-04 14-04-33](https://user-images.githubusercontent.com/2078045/148063665-c2a54e14-ff17-4908-83a3-133379d0515c.png)

![Screenshot from 2022-01-04 14-04-21](https://user-images.githubusercontent.com/2078045/148063414-9538571b-7746-44e7-8618-65fb76849147.png)
![Screenshot from 2022-01-04 14-06-23](https://user-images.githubusercontent.com/2078045/148063602-c6564e41-0ed0-4714-8c3f-f3e092fcd1dc.png)

@jkilzi FYI this also updates the dialog in OCM

ACM PR https://github.com/open-cluster-management/console/pull/1065

2021-12-16 15:51 UTC, jkilzi commented
@rawagner lgtm, but...
@nirfarkas are you aware of this change? Are you happy with it?

2021-12-19 13:53 UTC, nirfarkas commented
Not really ):
Why not change to using this?
https://github.com/patternfly/patternfly/issues/4017
It's interactive takes less space and is more elegant.

2021-12-21 13:06 UTC, ShiranHi commented
Using this rich helper text: https://marvelapp.com/prototype/haechg7/screen/84022338
Also in the Jira ticket: https://issues.redhat.com/browse/MGMT-8444

2021-12-21 17:55 UTC, jkilzi commented on src/common/components/hosts/EditHostForm.tsx
> +                }
@ShiranHi Patternfly already provides dynamic helper texts.
Please see this example: https://www.patternfly.org/v4/components/helper-text#dynamic-list

2021-12-21 17:59 UTC, jkilzi requested changes

2021-12-21 17:59 UTC, jkilzi commented on src/common/components/hosts/EditHostForm.tsx
> +                }
@rawagner, @ShiranHi Patternfly already provides dynamic helper texts.
Please see this example: https://www.patternfly.org/v4/components/helper-text#dynamic-list

2021-12-22 10:38 UTC, jkilzi commented on src/common/components/hosts/EditHostForm.tsx
> +                }
We have already a task in order to align the PF spec in this regard.
See: https://issues.redhat.com/browse/MGMT-8275

2022-01-04 09:04 UTC, rawagner commented
allright, i misunderstood what this rich text component should represent. Sorry about that.
PR is now updated (pics included). 
@ShiranHi can you take a look again ? I've also added/changed some validation messages to properly reflect what we validate

2022-01-04 09:37 UTC, nirfarkas commented
@rawagner are the pics here updated?

2022-01-04 10:04 UTC, ShiranHi commented
Thanks @rawagner it looks good, I am happy to see it :)
Just wrapping up our call: "Must be unique" will be the first bullet point and we use the custom check and cross marks icons, as in [PF](https://www.patternfly.org/v4/components/helper-text/#dynamic-list).

2022-01-04 10:23 UTC, jkilzi commented
@rawagner we can really make use of a GIF here showing how it behaves

2022-01-04 10:43 UTC, jkilzi submitted a review, later dismissed

2022-01-04 13:02 UTC, rawagner commented
@nirfarkas I did not press `Update comment` ..so ehm no, screenshots were not updated :) 

Anyways I added a gif as @jkilzi suggested.

@ShiranHi 
- Moved `Must be unique` to top
- Added 'default' state when there is no value in the field. Note that the default state does not have bullets but minus icon since there is no option to have bullets in PF react

2022-01-04 13:46 UTC, jkilzi approved these changes

2022-01-05 14:19 UTC, merged