MGMT-10958: Hostname 'localhost4.localdomain4' and more should not be valid.
openshift-assisted/assisted-ui-lib pull request #1483
Opened 2022-06-29 12:03 UTC by DanielleChason

https://issues.redhat.com/browse/MGMT-10958

**List of forbidden names:** 
![image](https://user-images.githubusercontent.com/69599321/176431596-21258c36-fdcb-430b-949e-433dca485f92.png)

**When a user tries to changes to such name:** 
![image](https://user-images.githubusercontent.com/69599321/176431464-e0821662-0271-4f1a-8908-e2074fbc00a2.png)

2022-06-29 14:18 UTC, jkilzi requested changes

2022-06-30 08:18 UTC, DanielleChason commented on src/common/components/ui/formik/constants.tsx
> +  LOCALHOST_ERR: 'Do not use forbidden words, for example: "localhost".',
@y0n1 
@nirfarkas  said this text for the validation should be:
Does not use forbidden names. For example, "localhost".

2022-07-01 06:55 UTC, jkilzi requested changes

2022-07-01 06:55 UTC, jkilzi commented on src/common/components/ui/formik/constants.tsx
> +  LOCALHOST_ERR: 'Cannot be a name that resolves to a loopback address.',
```suggestion
  LOCALHOST_ERR: 'Does not use forbidden names. For example, "localhost"',
```

2022-07-04 06:42 UTC, jkilzi approved these changes

2022-07-04 08:06 UTC, celdrake approved these changes

2022-07-06 14:40 UTC, merged