MGMT-10944 - SNO cluster should not allow adding more than 1 static IP configuration
openshift-assisted/assisted-ui-lib pull request #1506
Opened 2022-07-14 10:01 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-10944

**SNO:**
![image](https://user-images.githubusercontent.com/87187179/178956549-4f2c2bab-5479-4067-938b-156e7231345e.png)
![image](https://user-images.githubusercontent.com/87187179/178956790-686da63b-d26d-4437-b907-304a8e1be9a2.png)

**MNO:**
![image](https://user-images.githubusercontent.com/87187179/178957212-5885ab11-4232-45f1-bd95-c8c52e5e4559.png)
![image](https://user-images.githubusercontent.com/87187179/178956878-3033c908-6ab5-4250-93ce-7ef5be9089ce.png)

2022-07-14 10:28 UTC, jelkosz commented
can you maybe add a test for this?

2022-07-18 08:01 UTC, celdrake requested changes
Glad to see it worked! 

Let's remember it when we're working in components which may have unnecessary `isSNO` props.

2022-07-18 08:01 UTC, celdrake commented on src/ocm/components/clusterConfiguration/staticIp/components/StaticIpHostsArray.tsx
> +                data-testid="copy-host-cofiguration"
Could you please fix the typo in this `testid` ?

2022-07-18 08:45 UTC, celdrake approved these changes

2022-07-20 20:02 UTC, jkilzi approved these changes

2022-07-21 14:38 UTC, merged