MGMT-9659: Clarify on the Host Discovery instructions
openshift-assisted/assisted-ui-lib pull request #1517
Opened 2022-07-18 13:38 UTC by DanielleChason

https://issues.redhat.com/browse/MGMT-9659

![host-discovery](https://user-images.githubusercontent.com/77008341/182809622-aef80f07-550a-4f89-b976-b20e4d99ab7e.png)

2022-07-18 14:33 UTC, jkilzi requested changes

2022-07-21 07:21 UTC, celdrake commented
@jkilzi Do we want to include this as part of 2.7 given we did changes on Host Discovery for the same version?

2022-07-21 14:20 UTC, jkilzi commented
> @jkilzi Do we want to include this as part of 2.7 given we did changes on Host Discovery for the same version?

yep, makes sense to have it too

2022-07-21 14:21 UTC, jkilzi commented
@DanielleChason PTAL, your PR has merge conflicts

2022-08-04 06:55 UTC, celdrake approved these changes

2022-08-04 09:11 UTC, jkilzi approved these changes

2022-08-04 09:21 UTC, merged