Bug 2125584: Notify user about pending validations in day2 operations
openshift-assisted/assisted-ui-lib pull request #1635
Opened 2022-09-13 12:28 UTC by rawagner

2022-09-13 13:10 UTC, celdrake approved these changes

2022-09-14 08:25 UTC, celdrake approved these changes

2022-09-19 08:20 UTC, jtomasek requested changes

2022-09-19 08:20 UTC, jtomasek commented on src/cim/components/Hypershift/DetailsPage/NodePoolStatus.tsx
> +                    />
This one is repeating, maybe put it in a variable?

2022-09-20 08:21 UTC, jtomasek approved these changes

2022-09-20 08:42 UTC, ammont82 approved these changes

2022-09-20 08:49 UTC, merged