Fix Typescript errors
openshift-assisted/assisted-ui-lib pull request #1663
Opened 2022-09-28 12:02 UTC by guillaumevincent

2022-09-28 12:07 UTC, guillaumevincent commented
Here https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/ocm/components/clusters/ClusterPage.tsx#L66 resetCluster  expects a Promise. And forceReload is a redux action. I don't understand how it's working because we never dispatch the action. I bet it's not working.

I transformed the function into an async function

```
  const forceReloadAsync = () =>
    new Promise<void>((resolve) => {
      dispatch(forceReload());
      resolve();
    });
```

But maybe we can transform resetCluster into a basic function instead of a promise.

2022-09-28 12:39 UTC, celdrake commented
> Here https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/ocm/components/clusters/ClusterPage.tsx#L66 resetCluster expects a Promise. And forceReload is a redux action. I don't understand how it's working because we never dispatch the action. I bet it's not working.
> 
> I transformed the function into an async function
> 
> ```
>   const forceReloadAsync = () =>
>     new Promise<void>((resolve) => {
>       dispatch(forceReload());
>       resolve();
>     });
> ```
> 
> But maybe we can transform resetCluster into a basic function instead of a promise.

It's weird, as you say I think it must not have worked until now.
This would imply a few changes in `use-hosts-table` + testing so maybe for now let's keep it with your changes.

2022-09-28 17:14 UTC, rawagner requested changes

2022-09-28 17:14 UTC, rawagner commented on src/cim/components/featureSupportLevels/ACMFeatureSupportLevelProvider.tsx
> +      return getFeatureDisabledReason(featureId, undefined, isSupported, (s: string) => s);
you should pass `t` from `i18n`

```suggestion
      return getFeatureDisabledReason(featureId, undefined, isSupported, t);
```

```ts

import { useTranslation } from '../../../common/hooks/use-translation-wrapper';
...
const { t } = useTranslation();
...
return getFeatureDisabledReason(featureId, undefined, isSupported, t);
```

2022-09-29 11:21 UTC, guillaumevincent commented on src/cim/components/featureSupportLevels/ACMFeatureSupportLevelProvider.tsx
> +      return getFeatureDisabledReason(featureId, undefined, isSupported, (s: string) => s);
done thank you

2022-09-29 11:22 UTC, guillaumevincent commented on src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
> -                    labelInfo={index === 0 && isDualStack ? 'Primary' : ''}
I rollback my change, I don't fully understand why the linter think OcmInputField is InputFieldProps only

2022-09-29 11:26 UTC, guillaumevincent commented
Please take special attention to this pull request. I have not tested live. I'm not very confident with this resetCluster change. If it was working before, then we should find a way to test the new behavior.

I'm also okay to put this PR on hold or draft if needed.

2022-09-29 12:29 UTC, celdrake commented on src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
> -                    labelInfo={index === 0 && isDualStack ? 'Primary' : ''}
The problem is here: https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/ocm/components/ui/OcmFormFields.tsx#L49
The proper definition should match that of `InputField`

2022-09-29 12:30 UTC, celdrake commented
@guillaumevincent I suggest we split the issue about `resetCluster` until we can test it. Otherwise it may take a long time to merge

2022-10-07 10:47 UTC, celdrake commented on src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
> -                    labelInfo={index === 0 && isDualStack ? 'Primary' : ''}
It's been fixed already in `master`

2022-10-21 07:16 UTC, closed without merging

2022-10-21 07:16 UTC, guillaumevincent commented
closing for now, create more noise than help