MGMT-12335 - Next and back buttons should be aligned with cluster status in readonly
openshift-assisted/assisted-ui-lib pull request #1724
Opened 2022-11-07 11:15 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-12335

**Before:**
![image](https://user-images.githubusercontent.com/87187179/200297002-bc52bcb7-21ed-42d0-acb3-8a48a165a742.png)

**After:**
![image](https://user-images.githubusercontent.com/87187179/200296735-e0bf9e1b-8b43-4e14-964b-53116b5f17b9.png)

2022-11-07 11:35 UTC, celdrake commented
@jgyselov So we want the "read-only" user to have the same kind of restrictions that the people with write privileges do?
That means that for example, if a host is disconnected, and the "read-only" user would like to look at the network configuration, we would be blocked since they can't fix the validations issues, and they wouldn't be allowed to proceed to next step.

Anyway, if that's the behaviour that we want, then I think other changes are needed. For example, in `handleOnNext` in  `ClusterDetailsForm`, (and I'm not sure if in other places too).

2022-11-07 11:37 UTC, celdrake requested changes

2022-11-07 11:37 UTC, celdrake commented on src/ocm/components/clusterWizard/ClusterWizardFooter.tsx
> +      isNextDisabled={isNextDisabled}
The prop can be removed as it would be part of `rest`

2022-11-07 13:08 UTC, jgyselov commented
> So we want the "read-only" user to have the same kind of restrictions that the people with write privileges do? That means that for example, if a host is disconnected, and the "read-only" user would like to look at the network configuration, they would be blocked since they can't fix the validations issues, and they wouldn't be allowed to proceed to next step.

Yes, that's what the ticket is about. The question, I guess, is what use to the users is the information in the steps they would be blocked from accessing? And if a user should be able to see that information in read-only mode and not otherwise?

> Anyway, if that's the behaviour that we want, then I think other changes are needed. For example, in `handleOnNext` in `ClusterDetailsForm`, (and I'm not sure if in other places too).

```
const handleOnNext = (
    dirty: boolean,
    submitForm: FormikHelpers<unknown>['submitForm'],
    cluster?: Cluster,
  ): (() => Promise<void> | void) => {
    if (isViewerMode || (!dirty && !isUndefined(cluster) && canNextClusterDetails({ cluster }))) {
      return moveNext;
    }
    return submitForm;
  };
```

Why would that need to change? We still don't want to submit the form when you press Next in read only? Or am I missing something?

@celdrake

2022-11-07 13:20 UTC, celdrake commented
> 

 Why would that need to change? We still don't want to submit the form when you press Next in read only? Or am I missing something?
> 
> @celdrake

@jgyselov You are right, I got confused. Looks like the control is in the `ClusterWizardFooter` for all cases, so the change you did is enough.

2022-11-08 11:20 UTC, celdrake approved these changes

2022-11-08 11:35 UTC, ammont82 approved these changes

2022-11-08 14:13 UTC, merged