MGMT-11041: Enhance Add-hosts tab features
openshift-assisted/assisted-ui-lib pull request #1769
Opened 2022-11-29 15:15 UTC by celdrake

The "add hosts" tab in OCM to display the Day2 flow is changing:

- In certain cases, we want to hide the tab, same as what's happening
- In other cases, we want to disable the tab, and to show a tooltip as to why the tab is disabled
- In other cases, we want to let the user click the tab, and to show a message explaining why the Day2 flow is not shown.

TBD images when final UX and copy is received.

2022-12-13 12:27 UTC, jgyselov commented
> 3\. The tab is disabled, and show a tooltip as to why it's like that
> 
> * The cluster was not created with Assisted Installer
>   ![not-ai](https://user-images.githubusercontent.com/829045/207308253-71c2eeb6-1330-45db-b41a-c8c0f60a6a34.png)

I thought we agreed in the initial meeting that a cluster was not installed using Assisted Installer, we would not show the tab at all?

2022-12-13 13:16 UTC, jgyselov requested changes

2022-12-13 13:16 UTC, jgyselov commented on src/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
> +            We're waiting for your recently installed cluster to report its metrics.
```suggestion
             We're waiting for your recently installed cluster to report its metrics.{' '}
 ```

2022-12-13 14:03 UTC, celdrake commented
> > * The cluster was not created with Assisted Installer

> I thought we agreed in the initial meeting that a cluster was not installed using Assisted Installer, we would not show the tab at all?

We did, but the conversation continued in the shared Doc and later it was agreed that it should be shown in this case too.

2022-12-13 14:04 UTC, celdrake commented on src/ocm/components/HostsClusterDetailTab/utils.ts
> +  }
As mentioned before, the final agreement was to include this copy in the disabled tab for clusters not created with AI.

2022-12-13 14:05 UTC, celdrake commented on src/ocm/components/HostsClusterDetailTab/utils.ts
> +  // This is a multi-node cluster that supports the AI Day2 flow
True, it can also be an SNO which does support node expansion!

2022-12-13 14:36 UTC, celdrake commented on src/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
> +      if (day1ClusterHostCount === 0 || !Day2ClusterService.getOpenshiftClusterId(ocmCluster)) {
True, I missed it wouldn't work here. I'll move it up in the code.

2022-12-13 14:53 UTC, celdrake commented
@jgyselov I also fixed an spacing issue with the new banner for troubleshooting etc, it was just below the "add hosts" button in Day2 flow without any separation. 

It will look like this:
![spacing](https://user-images.githubusercontent.com/829045/207366176-92dbe273-0844-446d-8950-76fa2d218db0.png)

2022-12-13 14:54 UTC, jgyselov commented
> @jgyselov I also fixed an spacing issue with the new banner for troubleshooting etc, it was just below the "add hosts" button in Day2 flow without any separation.
> 
> It will look like this: ![spacing](https://user-images.githubusercontent.com/829045/207366176-92dbe273-0844-446d-8950-76fa2d218db0.png)

Awesome! Thank you :+1:

2022-12-13 14:55 UTC, celdrake commented on src/ocm/components/HostsClusterDetailTab/utils.ts
> +  }
Made the tab hidden if it's not an AI cluster after the latest agreement about it.

2022-12-13 14:57 UTC, jgyselov commented on src/ocm/components/HostsClusterDetailTab/utils.ts
> +  }
Great, thank you :slightly_smiling_face:

2022-12-13 15:58 UTC, jgyselov approved these changes

2022-12-15 06:15 UTC, ammont82 approved these changes

2022-12-15 07:43 UTC, celdrake commented
I'll hold off to merge this PR at about the last moment because it won't work with current uhc-portal.

2023-01-02 07:30 UTC, nirfarkas commented
@celdrake 
The cluster was not created with Assisted Installer
I thought we agreed in the initial meeting that a cluster was not installed using Assisted Installer, we would not show the tab at all?

We did, but the conversation continued in the shared Doc and later it was agreed that it should be shown in this case too.

I think we've decided to hide the tab if it was not created using AI. See doc last bullet:
https://docs.google.com/document/d/1npxyYH98mF1RcmKBeGAKFFKiE6AYj_H634SvqZY2keA/edit#

2023-01-02 09:46 UTC, jkilzi approved these changes

2023-01-02 10:17 UTC, jkilzi commented
> @celdrake The cluster was not created with Assisted Installer I thought we agreed in the initial meeting that a cluster was not installed using Assisted Installer, we would not show the tab at all?
> 
> We did, but the conversation continued in the shared Doc and later it was agreed that it should be shown in this case too.
> 
> I think we've decided to hide the tab if it was not created using AI. See doc last bullet: https://docs.google.com/document/d/1npxyYH98mF1RcmKBeGAKFFKiE6AYj_H634SvqZY2keA/edit#

This has already been addressed [here](https://github.com/openshift-assisted/assisted-ui-lib/pull/1769/files#diff-3311b991deaf9714f0ebc2d401d88cba38ea0f17fe32ffcd679c4ff0b4c20f84R31-R36). The tab will be hidden when the cluster was not created using assisted installer

2023-01-02 10:18 UTC, merged