MGMT-11370 -  After discovery, if deleting all discovered hosts UI still allows to continue to networking and R&C pages
openshift-assisted/assisted-ui-lib pull request #1779
Opened 2022-12-06 14:57 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-11370

The [changes done to the BE](https://issues.redhat.com/browse/MGMT-11536) seem to have fixed the majority of this bug. I'm adding a reload of the cluster after hosts are deleted (or renamed) so that the changes are immediately visible. Whereas before we would have to wait for the next polling cycle to see the changes.

**Before:**

https://user-images.githubusercontent.com/87187179/207077971-be41027b-a02b-4633-8110-928169c2a988.mp4

**After:**

https://user-images.githubusercontent.com/87187179/207078026-3d9b194d-f055-41d8-9f07-f6408cea3bfb.mp4

2022-12-06 19:02 UTC, jkilzi commented
@jgyselov could you please attach a demo?

2022-12-07 06:11 UTC, ammont82 submitted a review, later dismissed

2022-12-12 08:50 UTC, celdrake requested changes

2022-12-12 08:50 UTC, celdrake commented on src/common/components/hosts/MassDeleteHostModal.tsx
> +  reloadCluster: VoidFunction;
This property should be optional given that `InfraEnvAgentTable` in CIM uses this component.

Same in `MassChangeHostnameModal`

2022-12-12 16:05 UTC, celdrake approved these changes

2022-12-12 16:11 UTC, ammont82 approved these changes

2022-12-13 07:36 UTC, merged