MGMT-13046: Add missing translation for console dialog
openshift-assisted/assisted-ui-lib pull request #1837
Opened 2023-01-02 09:36 UTC by jtomasek

Fixes MGMT-13046

2023-01-02 09:45 UTC, ammont82 requested changes
Don't touch the i18n.sh script because these changes only work in your computer

2023-01-02 09:57 UTC, jtomasek commented
@ammont82 fixed, sorry

2023-01-02 09:58 UTC, ammont82 approved these changes

2023-01-02 10:12 UTC, ammont82 approved these changes

2023-01-03 09:32 UTC, mareklibra approved these changes

2023-01-03 11:12 UTC, merged