MGMT-12901- Align the section title for 'IPv4 / Dual-stack' selection in Static network configurations and Networking steps in AI wizard
openshift-assisted/assisted-ui-lib pull request #1903
Opened 2023-02-01 13:13 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-12901

**Before:**
![image](https://user-images.githubusercontent.com/87187179/216052692-99ad8227-fb80-432d-9280-82c06602655a.png)

**After:**
![image](https://user-images.githubusercontent.com/87187179/216051764-51f63329-5b06-4230-a55c-17b38a691d1d.png)

2023-02-01 13:29 UTC, celdrake requested changes

2023-02-01 13:29 UTC, celdrake commented on src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx
>          options={protocolVersionOptions}
I think we should be applyng this same name change to the components themselves.

eg. `protocolVersionOptions`, `setProtocolType`, etc

2023-02-01 14:18 UTC, celdrake commented on src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx
>          options={protocolVersionOptions}
Feel fee to sync with @ammont82 as I noticed there is another PR modifyng this component, so the renaming can be done there if you prefer
https://github.com/openshift-assisted/assisted-ui-lib/pull/1889/files

2023-02-08 08:17 UTC, celdrake approved these changes

2023-02-08 09:05 UTC, ammont82 approved these changes

2023-02-08 09:11 UTC, merged