MGMT-13728 - Platform helper text should be reformatted
openshift-assisted/assisted-ui-lib pull request #1952
Opened 2023-02-28 12:47 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-13728

**Before:**
![image](https://user-images.githubusercontent.com/87187179/221858222-0b8571b3-504a-465b-8eb1-7252427b3503.png)

**After:**
![image](https://user-images.githubusercontent.com/87187179/221857785-cff82c89-faf2-4e92-920a-ae46d2117cb9.png)

2023-03-06 06:25 UTC, ammont82 approved these changes

2023-03-06 07:09 UTC, jkilzi requested changes

2023-03-06 07:09 UTC, jkilzi commented on src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx
> +              </Text>
Can't we do just this?
```suggestion
              <Text>{messages[supportedPlatformIntegration]}</Text>
```

2023-03-07 10:50 UTC, jgyselov commented on src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx
> +              </Text>
We can.

2023-03-07 10:51 UTC, ammont82 approved these changes

2023-03-12 12:31 UTC, jkilzi approved these changes

2023-03-13 06:32 UTC, merged