refactor(bug-fix):  missing "Hardware Type" value in physical hosts
openshift-assisted/assisted-ui-lib pull request #409
Opened 2021-01-13 23:06 UTC by jkilzi

Addresses an issue where the "Hardware Type" value in physical hosts was missing.

2021-01-19 07:57 UTC, mareklibra commented
Is there a bug for that? If so, please change the title to
```
BZ 123456: missing "Hardware Type" value in physical hosts
```
Or of the issue is tracked in jira:
```
MGMT-1234: missing "Hardware Type" value in physical hosts
```
This rule helps while composing release notes.

2021-01-20 12:45 UTC, jtomasek requested changes

2021-01-20 12:45 UTC, jtomasek commented on src/components/hosts/HostRowDetail.tsx
> +  const virtualText = getHardwareTypeText(inventory);
Nit: `virtualText` is a bit confusing

```suggestion
  const hardwareType = getHardwareTypeText(inventory);
```

2021-01-20 14:02 UTC, jtomasek approved these changes

2021-01-20 14:13 UTC, merged