MGMT-3333: Show CVO in the UI
openshift-assisted/assisted-ui-lib pull request #412
Opened 2021-01-20 15:11 UTC by irosenzw

Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>

2021-01-20 15:21 UTC, mareklibra commented on src/components/clusterDetail/ClusterProgress.tsx
> +    <div>
nit: just fragment `<>` would be enough

2021-01-20 15:47 UTC, jtomasek requested changes

2021-01-20 15:47 UTC, jtomasek commented on src/components/clusterDetail/ClusterProgress.tsx
> +                <div>
```suggestion
                <TextContent>
```

2021-01-20 15:47 UTC, jtomasek commented on src/components/clusterDetail/ClusterProgress.tsx
> +                  <div>
```suggestion
                  <Text>
```

2021-01-20 15:47 UTC, jtomasek commented on src/components/clusterDetail/ClusterProgress.tsx
> +                <>
```suggestion
                <TextContent>
```

2021-01-20 15:47 UTC, jtomasek commented on src/components/clusterDetail/ClusterProgress.tsx
> +                  <Button
The button can be put into Popover footer

2021-01-20 15:47 UTC, jtomasek commented on src/components/clusterDetail/ClusterProgress.tsx
>    const { status, hosts } = cluster;
```suggestion
  const { status, hosts = [] } = cluster;
```

2021-01-20 15:47 UTC, jtomasek commented on src/components/clusterDetail/ClusterProgress.tsx
> +          <HostProgress hosts={cluster.hosts as Host[]} hostRole="master" />
```suggestion
          <HostProgress hosts={hosts} hostRole="master" />
```

2021-01-20 15:47 UTC, jtomasek commented on src/components/clusterDetail/ClusterProgress.tsx
> +            <HostProgress hosts={cluster.hosts as Host[]} hostRole="worker" />
```suggestion
            <HostProgress hosts={hosts} hostRole="worker" />
```

2021-01-20 18:19 UTC, jtomasek requested changes

2021-01-20 22:21 UTC, andybraren commented
Screenshots please 🙏

2021-01-25 10:17 UTC, nirfarkas commented
@irosenzw I’ve got feedback on the “Pending” icon and changed it in the [mock](https://marvelapp.com/prototype/f2j8hh7/screen/72564353)

2021-01-27 10:02 UTC, jtomasek approved these changes

2021-01-27 10:08 UTC, merged