WIP MGMT-3236 Add ReviewStep to wizard
openshift-assisted/assisted-ui-lib pull request #425
Opened 2021-01-27 12:13 UTC by mareklibra

This PR is heavily WIP.

Depends on:
- [ ] #3235

2021-01-27 16:37 UTC, mareklibra commented
![01](https://user-images.githubusercontent.com/17194943/106022644-5c1b0d80-60c6-11eb-9168-0e9b2ecc94bd.png)

2021-01-28 14:15 UTC, mareklibra commented
![02](https://user-images.githubusercontent.com/17194943/106150473-af9b6300-617b-11eb-82ff-8dd12a611ca2.png)

Cc @nirfarkas

2021-01-28 15:02 UTC, jtomasek requested changes

2021-01-28 15:07 UTC, mareklibra commented on src/components/clusterConfiguration/ReviewStep.tsx
> +    <Grid hasGutter>
Thanks

2021-01-28 15:11 UTC, jtomasek approved these changes

2021-01-28 15:12 UTC, merged