Introduce wizard step validation mapping
openshift-assisted/assisted-ui-lib pull request #453
Opened 2021-02-12 15:05 UTC by jtomasek

- Use validation map to calculate cluster/host validationInfo and
  status
- Use calculated status to determine transition to next step
- Adjust ClusterWizardToolbar to display validations toggle properly
- Simplify 'canNext' functions
- Enable 'Next' button in case when form is dirty and valid to allow
  user saving the changes regardless of backend validations

2021-02-12 15:26 UTC, mareklibra requested changes

2021-02-12 15:26 UTC, mareklibra commented on src/components/clusterConfiguration/NetworkConfigurationForm.tsx
> +                isNextDisabled={!(isValid && dirty) && !canNextNetwork({ cluster })}
If the form is dirty and valid, it should be possible to submit it no matter of former validation state.

2021-02-12 15:26 UTC, mareklibra commented on src/components/clusterWizard/wizardTransition.ts
> +    validationIds: [/*'sufficient-masters-count',*/ 'ocs-requirements-satisfied'],
please reference https://bugzilla.redhat.com/show_bug.cgi?id=1928086 here

2021-02-12 15:26 UTC, mareklibra commented on src/components/clusterConfiguration/ClusterValidationSection.tsx
> +                      <ListItem key={validation.id}>{validation?.message}</ListItem>
not needed

2021-02-15 09:22 UTC, jtomasek commented on src/components/clusterConfiguration/ClusterValidationSection.tsx
> +                      <ListItem key={validation.id}>{validation?.message}</ListItem>
done

2021-02-15 09:22 UTC, jtomasek commented on src/components/clusterWizard/wizardTransition.ts
> +    validationIds: [/*'sufficient-masters-count',*/ 'ocs-requirements-satisfied'],
done

2021-02-16 10:46 UTC, mareklibra approved these changes

2021-02-16 10:46 UTC, merged