API Updates
openshift-assisted/assisted-ui-lib pull request #514
Opened 2021-03-16 09:30 UTC by jtomasek

- Update api/types.ts according to latest swagger
- Support new preparing-successful host status
- Support new host validations
- Adjust cluster and hosts validation groups
- Update OCS checkbox to use latest operators API

2021-03-16 13:27 UTC, jkilzi requested changes

2021-03-16 13:39 UTC, jkilzi submitted a review, later dismissed

2021-03-17 07:58 UTC, mareklibra commented on src/config/constants.ts
> +  'container-images-available': '',
We need to double check those in the context of wizard's transitions

2021-03-17 07:58 UTC, mareklibra approved these changes

2021-03-18 09:08 UTC, mareklibra approved these changes

2021-03-18 09:08 UTC, merged