BZ1954106 Fix updates of Formik's initialValues
openshift-assisted/assisted-ui-lib pull request #585
Opened 2021-05-05 09:54 UTC by mareklibra

2021-05-05 10:05 UTC, jtomasek requested changes
Calling `setInitialValues` is the same as using Formik's `resetForm` and resetForm does not need `enableReinitialize`.

We've used `resetForm` before introducing autosave to reset the form once it has been updated by a response from the server. And I agree that it is correct way to ensure the form becomes not dirty and reflects the changes which backend did.

The reason why we removed usage of resetForm is that it introduces a race condition between server responding and user typing. E.g.: User types in an IP, stops typing for 2 seconds which triggers autosave and a request is submitted. User starts typing again, and in the meantime a response from server arrives. At that point we call `resetForm` and that overrides the value which user typed while request has been handled by server.

2021-05-05 10:10 UTC, jkilzi reviewed
lgtm

2021-05-05 10:52 UTC, mareklibra commented
The use of `resetForm` or React's state seems to be semantically equal, I am ok to use any of those.
Let's consider the rewrites.

2021-05-05 13:35 UTC, jtomasek commented
I would prefer using `resetForm` as it is a standard API of the Formik and it ensures that things will work as expected, compared to a custom solution which works exactly the same

2021-05-05 13:37 UTC, jtomasek commented
We should think about how we'll go about bugs which will be filed on the issue I mentioned above. IMHO at that point we'd have to reconsider whether we do or don't want the autosave functionality

2021-05-05 14:38 UTC, mareklibra commented
Switched to `resetForm`

2021-05-06 09:51 UTC, jtomasek requested changes

2021-05-06 09:51 UTC, jtomasek commented on src/components/clusterConfiguration/NetworkConfigurationForm.tsx
> +        values: getNetworkInitialValues(cluster, defaultNetworkSettings),
```suggestion
        values: getNetworkInitialValues(data, defaultNetworkSettings),
```

2021-05-06 09:51 UTC, jtomasek commented on src/components/clusterWizard/HostDiscovery.tsx
> +      actions.resetForm({ values: getHostDiscoveryInitialValues(cluster) });
```suggestion
      actions.resetForm({ values: getHostDiscoveryInitialValues(data) });
```

2021-05-06 10:17 UTC, jtomasek commented
I've tested this with Formik 2.2.6 and it works as expected. The collision between reseting the form and user input is present but it is a tradeof of autosave functionality.

We could update Formik to 2.2.6 as part of this change or a subsequent one.

2021-05-06 10:32 UTC, mareklibra commented
I will update Formik in #586

2021-05-06 10:50 UTC, jtomasek approved these changes

2021-05-06 10:53 UTC, merged