MGMT-7701 - Guide users to set vsphere configuration after the installation
openshift-assisted/assisted-ui-lib pull request #775
Opened 2021-09-03 12:27 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-7701

**Todo:**
- [ ] Have microcopy aproved
- [ ] Change link address
- [ ] Try out on an actual cluster

![image](https://user-images.githubusercontent.com/87187179/132004658-5afdd920-2d2e-4d9a-baa7-1840ec648187.png)
![alert](https://user-images.githubusercontent.com/87187179/132005032-3cd74b23-a3a5-4b41-9d9e-617713c04e14.png)

2021-09-05 11:11 UTC, nirfarkas commented
We might need to change the "Learn more" external link text to be more specific. Please take a look at the Jira story discussion.

2021-09-05 18:43 UTC, jkilzi commented
I believe it will be best to receive the platform-specific configuration docs from the BE. In this way, the information will be maintained in a single place. Otherwise, we'll be forced to hold links (hard-coded) in our code for every platform we'll support in the future.

2021-09-09 21:17 UTC, jkilzi requested changes

2021-09-09 21:17 UTC, jkilzi commented on src/ocm/components/clusterDetail/ClusterDetail.tsx
> +                    href="https://issues.redhat.com/secure/attachment/12531134/12531134_How+to+modify+the+vSphere+configuration+in+OpenShift+4.x+-+Red+Hat+Customer+Portal.pdf"
@jgyselov  please put this URL inside `src/common/config/constants.ts`

2021-09-12 12:11 UTC, jkilzi approved these changes

2021-09-12 12:17 UTC, merged