WIP ACM: Add Logs and Events download for an installed cluster
openshift-assisted/assisted-ui-lib pull request #869
Opened 2021-10-05 12:53 UTC by mareklibra

2021-10-05 12:57 UTC, mareklibra commented on src/cim/components/ClusterDeployment/helpers.ts
> +// https://localhost:4000/multicloud/api/v1/namespaces/assisted-installer/services/https:assisted-service:8090/proxy/api/assisted-install/v1/clusters/ad0409d7-1798-4459-85a9-480d6d36f369/logs?api_key
So far the proxy is complaining during TLS handshake

2021-10-05 13:54 UTC, mareklibra commented on src/cim/components/ClusterDeployment/helpers.ts
> +// https://localhost:4000/multicloud/api/v1/namespaces/assisted-installer/services/https:assisted-service:8090/proxy/api/assisted-install/v1/clusters/ad0409d7-1798-4459-85a9-480d6d36f369/logs?api_key
Fixed: It was caused by changed AI-service namespace for the proxy

2021-10-06 08:45 UTC, jtomasek requested changes
The code for events fetch handling is duplicated here: https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/cim/components/ClusterDeployment/ClusterDeploymentProgress.tsx#L112

So based on my comments [here](https://github.com/open-cluster-management/console/pull/907#pullrequestreview-772362877) we should use getFetchEventsHandler(fetchEvents, agentClusterInstall) there.

2021-10-06 09:07 UTC, jtomasek approved these changes

2021-10-06 09:08 UTC, merged