MGMT-4551: Add 'Run workloads on control plane node' switch
openshift-assisted/assisted-ui-lib pull request #947
Opened 2021-11-08 20:38 UTC by batzionb

2021-11-09 08:57 UTC, jkilzi commented on src/common/components/hosts/RoleDropdown.tsx
>    const [isDisabled, setDisabled] = React.useState(false);
Please change `useStateSafely`

2021-11-09 12:34 UTC, jkilzi requested changes

2021-11-09 12:41 UTC, batzionb commented on src/common/components/hosts/utils.ts
> +    HOST_ROLES.find((role) => role.value === host.role)?.label || HOST_ROLES[0].label
We agreed with Nir that we are removing it

2021-11-10 09:06 UTC, batzionb commented on src/common/components/hosts/RoleDropdown.tsx
>    const [isDisabled, setDisabled] = React.useState(false);
fixed

2021-11-10 15:09 UTC, jkilzi approved these changes

2021-11-10 15:10 UTC, merged